//go:build ignore

package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
)

func main() {
	// Read the JSON mapping
	file, err := os.ReadFile("resources/mcc_risk.json")
	if err != nil {
		log.Fatalf("Failed to read mcc_risk.json: %v", err)
	}

	var riskMap map[string]float32
	if err := json.Unmarshal(file, &riskMap); err != nil {
		log.Fatalf("Failed to parse mcc_risk.json: %v", err)
	}

	// Create output file
	out, err := os.Create("mcc_data.go")
	if err != nil {
		log.Fatalf("Failed to create mcc_data.go: %v", err)
	}
	defer out.Close()

	// Metaprogramming: Generate the Go source file containing the O(1) array
	fmt.Fprintln(out, "// Code generated by tools/mccgen.go. DO NOT EDIT.")
	fmt.Fprintln(out, "package main")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "// MccRisk is a pre-computed array for O(1) MCC risk lookups.")
	fmt.Fprintln(out, "var MccRisk = [10000]float32{")

	for i := 0; i < 10000; i++ {
		codeStr := fmt.Sprintf("%04d", i)
		val, exists := riskMap[codeStr]
		
		// If MCC is not found or invalid, default to 0.5 (medium risk)
		if !exists {
			val = 0.5
		}

		// Hardcode the floating point value into the array definition
		fmt.Fprintf(out, "\t%d: %f,\n", i, val)
	}

	fmt.Fprintln(out, "}")
	log.Println("Successfully generated mcc_data.go with 10000 O(1) mapping indices.")
}
